Reland "add regexp_benchmark target"
This reverts commit 5968df03326f7b0bf4ba0f5c5b93ed9467ddb700.

This patch includes the fix for the following error that
caused it to be reverted by commit 5968df03326f:

re2/testing/dump.cc:21:23: fatal error: util/test.h: No such file or
directory
 #include "util/test.h"

Change-Id: I6f3fff1de809e61c6a9da64e24b606d2921529fa