Update patch set 2
Patch Set 2: Code-Review-1

$ bazel build --spawn_strategy=standalone --genrule_strategy=standalone //...
INFO: Found 25 targets...
ERROR: /tmp/re2/BUILD:179:1: Linking of rule '//:regexp_benchmark' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/regexp_benchmark -pthread -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld: bazel-out/local_linux-fastbuild/bin/libre2.a(dfa.pic.o): undefined reference to symbol 'ceil@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 0.120s, Critical Path: 0.03s

On my workstation it breaks even without sandboxing.

Patch-set: 2
Label: Code-Review=-1